package com.iab.gdpr.util

object GdprConstants {
  val BITS_PER_BYTE = 8
  val SIX_BITS = 6
  val VERSION_BIT_OFFSET = 0
  val VERSION_BIT_SIZE = 6
  val CREATED_BIT_OFFSET = 6
  val CREATED_BIT_SIZE = 36
  val UPDATED_BIT_OFFSET = 42
  val UPDATED_BIT_SIZE = 36
  val CMP_ID_OFFSET = 78
  val CMP_ID_SIZE = 12
  val CMP_VERSION_OFFSET = 90
  val CMP_VERSION_SIZE = 12
  val CONSENT_SCREEN_OFFSET = 102
  val CONSENT_SCREEN_SIZE = 6
  val CONSENT_LANGUAGE_OFFSET = 108
  val CONSENT_LANGUAGE_SIZE = 12
  val VENDOR_LIST_VERSION_OFFSET = 120
  val VENDOR_LIST_VERSION_SIZE = 12
  val PURPOSES_OFFSET = 132
  val PURPOSES_SIZE = 24
  val MAX_VENDOR_ID_OFFSET = 156
  val MAX_VENDOR_ID_SIZE = 16
  val ENCODING_TYPE_OFFSET = 172
  val ENCODING_TYPE_SIZE = 1
  val VENDOR_BITFIELD_OFFSET = 173
  val DEFAULT_CONSENT_OFFSET = 173
  val NUM_ENTRIES_OFFSET = 174
  val NUM_ENTRIES_SIZE = 12
  val RANGE_ENTRY_OFFSET = 186
  val VENDOR_ID_SIZE = 16
}
